# src/main/resources/application.properties

server.port=8181

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# =========================

spring.datasource.url=jdbc:mysql://mysql:3306/reception?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1111
# =========================
# MyBatis
# =========================
mybatis.mapper-locations=classpath:mapper/*.xml
<<<<<<< HEAD
mybatis.type-aliases-package=kr.co.seoulit.reception.dto
=======
mybatis.type-aliases-package=kr.co.seoulit.reception.outpatient.dto,kr.co.seoulit.reception.reservation.dto,kr.co.seoulit.reception.emergency.dto,kr.co.seoulit.reception.inpatient.dto
>>>>>>> 4ce2497 (- 접수 핵심 4개 + 확장 테이블 연동 로직 반영)
mybatis.configuration.map-underscore-to-camel-case=true

# =========================
# Logging
# =========================
logging.level.kr.co.seoulit.reception=DEBUG
logging.level.org.mybatis=DEBUG
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

# =========================
# Swagger (Springdoc)
# =========================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
<<<<<<< HEAD
=======


>>>>>>> 4ce2497 (- 접수 핵심 4개 + 확장 테이블 연동 로직 반영)
