DELETE FROM RECEPTION_TODAY_SCHEDULE WHERE SCHEDULE_DATE = TRUNC(SYSDATE);
DELETE FROM RECEPTION_CHECKLIST_ITEM WHERE CHECK_DATE = TRUNC(SYSDATE);

INSERT INTO RECEPTION_TODAY_SCHEDULE (SCHEDULE_ID, SCHEDULE_DATE, TIME_LABEL, TITLE, SORT_ORDER)
VALUES (RECEPTION_TODAY_SCHEDULE_SEQ.NEXTVAL, TRUNC(SYSDATE), '10:00', '정기 진료', 1);
INSERT INTO RECEPTION_TODAY_SCHEDULE (SCHEDULE_ID, SCHEDULE_DATE, TIME_LABEL, TITLE, SORT_ORDER)
VALUES (RECEPTION_TODAY_SCHEDULE_SEQ.NEXTVAL, TRUNC(SYSDATE), '11:30', '검사 결과 설명', 2);
INSERT INTO RECEPTION_TODAY_SCHEDULE (SCHEDULE_ID, SCHEDULE_DATE, TIME_LABEL, TITLE, SORT_ORDER)
VALUES (RECEPTION_TODAY_SCHEDULE_SEQ.NEXTVAL, TRUNC(SYSDATE), '15:00', '수술 상담', 3);

INSERT INTO RECEPTION_CHECKLIST_ITEM (CHECKLIST_ID, CHECK_DATE, LABEL, DONE, SORT_ORDER)
VALUES (RECEPTION_CHECKLIST_ITEM_SEQ.NEXTVAL, TRUNC(SYSDATE), '진료 일정 확인', 0, 1);
INSERT INTO RECEPTION_CHECKLIST_ITEM (CHECKLIST_ID, CHECK_DATE, LABEL, DONE, SORT_ORDER)
VALUES (RECEPTION_CHECKLIST_ITEM_SEQ.NEXTVAL, TRUNC(SYSDATE), '검사 결과 업로드', 0, 2);
INSERT INTO RECEPTION_CHECKLIST_ITEM (CHECKLIST_ID, CHECK_DATE, LABEL, DONE, SORT_ORDER)
VALUES (RECEPTION_CHECKLIST_ITEM_SEQ.NEXTVAL, TRUNC(SYSDATE), '처방 이력 검토', 0, 3);
INSERT INTO RECEPTION_CHECKLIST_ITEM (CHECKLIST_ID, CHECK_DATE, LABEL, DONE, SORT_ORDER)
VALUES (RECEPTION_CHECKLIST_ITEM_SEQ.NEXTVAL, TRUNC(SYSDATE), '미수금 확인', 0, 4);
COMMIT;