-- Reception dashboard tables (Oracle)
CREATE TABLE RECEPTION_TODAY_SCHEDULE (
    SCHEDULE_ID NUMBER(19) PRIMARY KEY,
    SCHEDULE_DATE DATE NOT NULL,
    TIME_LABEL VARCHAR2(10) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    SORT_ORDER NUMBER(10)
);

CREATE SEQUENCE RECEPTION_TODAY_SCHEDULE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE RECEPTION_CHECKLIST_ITEM (
    CHECKLIST_ID NUMBER(19) PRIMARY KEY,
    CHECK_DATE DATE NOT NULL,
    LABEL VARCHAR2(200) NOT NULL,
    DONE NUMBER(1) DEFAULT 0 NOT NULL,
    SORT_ORDER NUMBER(10)
);

CREATE SEQUENCE RECEPTION_CHECKLIST_ITEM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
